# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportZonePlugin
                                 A QGIS plugin
 Découpage des couches QGIS selon une zone d'étude dessinée ou issue de la BDD CEN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-12
        copyright            : (C) 2026 by LAKRIOUCH IKRAM
        email                : lakriouchikram@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportZonePlugin class from file ExportZonePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_sig_zone_etude import ExportZonePlugin
    return ExportZonePlugin(iface)
