# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportZonePluginDialog
                                 A QGIS plugin
 Découpage des couches QGIS selon une zone d'étude dessinée ou issue de la BDD CEN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by LAKRIOUCH IKRAM
        email                : lakriouchikram@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# -*- coding: utf-8 -*-
"""
Dialogue principal du plugin Export SIG Zone Etude.

Ce fichier charge l'interface .ui et connecte les widgets aux méthodes Python.

Compatibilité :
- QGIS 3.28+
- Préparation QGIS 4.x
- Imports Qt uniquement via qgis.PyQt
- Pas d'API privée QGIS
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtCore import QDate
from qgis.PyQt.QtWidgets import (
    QDialog,
    QFileDialog,
    QListWidgetItem,
)

from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsRasterLayer,
)

from .compat import (
    QT_CHECKED,
    QT_UNCHECKED,
    QT_USER_ROLE,
    QT_WINDOW_MINIMIZE_BUTTON_HINT,
    QT_WINDOW_MAXIMIZE_BUTTON_HINT,
    QT_WINDOW_CLOSE_BUTTON_HINT,
)
from .compat import (
    QSIZE_POLICY_PREFERRED,
    QSIZE_POLICY_EXPANDING,
    QSIZE_POLICY_MINIMUM,
    QSIZE_POLICY_FIXED,
    QSIZE_POLICY_IGNORED,
)



from .compat import exec_dialog, QDIALOG_ACCEPTED
from qgis.PyQt.QtWidgets import QDialog
from .site_cen_selection_dialog import SelecteurSiteCEN, charger_zone_bdd
from qgis.PyQt.QtWidgets import QMessageBox
from .outil_dessin import OutilDessinPolygone
from .zone_etude import ZoneEtude
from datetime import datetime
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox
from .export_logic import decouper_couches_par_zone

from qgis.PyQt.QtWidgets import QApplication
from qgis.PyQt.QtWidgets import QSizePolicy





FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        "export_sig_zone_etude_dialog_base.ui"
    )
)


class ExportZonePluginDialog(QDialog, FORM_CLASS):
    """
    Fenêtre principale du plugin.

    Fait le lien entre l'interface .ui et la logique de découpage
    (export_logic.decouper_couches_par_zone).
    """

    def __init__(self, iface=None, parent=None):
        """
        Constructeur du dialogue.

        :param iface: interface QGIS fournie par le plugin principal.
        :type iface: qgis.gui.QgisInterface
        :param parent: widget parent, généralement iface.mainWindow().
        """
        super().__init__(parent)
        self.iface = iface
        self.outil_dessin = None
        # Logs envoyés vers le journal QGIS, pas dans l'interface
        self.debug_logs = True
        # Chemin pg_service.conf
        self.pg_service_path = r"Q:\DATA_QGIS\PARAMETRAGE_QGIS\PG_SERVICE\pg_service.conf"
        # Zone d'étude courante
        self.zone_geometry = None
        self.zone_crs = None
        self.zone_source = None
        self.zone_etude = None
        # Site CEN sélectionné
        self.selected_codesitep = None
        self.selected_nomsitep = None
        self.selected_communes = None
        # Mémorise les couches cochées/décochées dans l'interface du plugin.
        # Clé = layer.id()
        # Valeur = état de coche Qt
        self.layer_check_states = {}
        # Charge l'interface .ui
        self.setupUi(self)
        # Configuration de la fenêtre
        self._configure_window_behavior()

                # Zone "Couches" plus grande et compatible QGIS 3 / QGIS 4
        try:
            QSIZE_POLICY = QSizePolicy.Policy
        except AttributeError:
            QSIZE_POLICY = QSizePolicy

        self.group_couches.setSizePolicy(
            QSizePolicy(
                QSIZE_POLICY.Preferred,
                QSIZE_POLICY.Expanding
            )
        )
        self.list_couches.setSizePolicy(
            QSizePolicy(
                QSIZE_POLICY.Expanding,
                QSIZE_POLICY.Expanding
            )
        )
        self.list_couches.setMinimumHeight(90)
        # Réduire la taille des boutons
        self.btn_actualiser_couches.setFixedHeight(24)
        self.btn_tout_selectionner_couches.setFixedHeight(24)
        self.btn_tout_deselectionner_couches.setFixedHeight(24)
        # Taille d'ouverture du plugin
        screen = QApplication.primaryScreen()
        if screen is not None:
            available = screen.availableGeometry()
            w = min(680, available.width() - 40)
            h = min(620, available.height() - 40)
            self.resize(w, h)
        else:
            self.resize(680, 620)
        # Taille minimale cohérente
        self.setMinimumSize(520, 520)
        # Connexions et initialisation
        self._connect_signals()
        self._init_defaults()
        self.refresh_visible_layers()
        self.line_suffixe.setText("export")
        self.update_output_filename()
        # Options
        self.init_options()
        self.progress_bar.setValue(0)


    def _configure_window_behavior(self):
        """
        Configure le comportement de la fenêtre :
        - minimisation ;
        - maximisation ;
        - fermeture ;
        - redimensionnement manuel.
        """
        flags = self.windowFlags()
        flags = (
            flags
            | QT_WINDOW_MINIMIZE_BUTTON_HINT
            | QT_WINDOW_MAXIMIZE_BUTTON_HINT
            | QT_WINDOW_CLOSE_BUTTON_HINT
        )
        self.setWindowFlags(flags)
        # Poignée de redimensionnement en bas à droite
        self.setSizeGripEnabled(True)
        # Taille minimale raisonnable
        self.setMinimumSize(520, 520)

    # -------------------------------------------------------------------------
    # Initialisation UI
    # -------------------------------------------------------------------------

    def _connect_signals(self):
        """
        Connecte les widgets du .ui aux méthodes Python.

        Compatibilité :
        - signaux Qt standards via qgis.PyQt ;
        - pas d'autoconnect Qt Designer, pour garder le code explicite.
        """

        # Zone d'étude
        self.radio_dessiner.toggled.connect(self.on_zone_mode_changed)
        self.radio_site_cen.toggled.connect(self.on_zone_mode_changed)
        self.btn_activer_dessin.clicked.connect(self.activate_draw_tool)

        self.radio_site_cen.clicked.connect(self.ouvrir_selecteur_site_cen)
        self.btn_activer_dessin.clicked.connect(self.activate_draw_tool)

        # Couches
        self.btn_actualiser_couches.clicked.connect(self.refresh_visible_layers)
        self.list_couches.itemChanged.connect(self.on_layer_item_changed)

        self.btn_tout_selectionner_couches.clicked.connect(self.select_all_layers)
        self.btn_tout_deselectionner_couches.clicked.connect(self.deselect_all_layers)

        # Sortie
        self.btn_parcourir_sortie.clicked.connect(self.browse_output_folder)
        self.line_dossier_sortie.textChanged.connect(self.update_output_filename)
        self.line_suffixe.textChanged.connect(self.update_output_filename)

        # Options
        self.check_pyramides_raster.toggled.connect(self.on_options_changed)
        self.combo_resolution_wms.currentIndexChanged.connect(self.on_options_changed)


        # Exécution
        self.btn_lancer_decoupage.clicked.connect(self.run_decoupage)

        # Fermeture
        self.btn_fermer.clicked.connect(self.reject)

    def on_site_cen_radio_clicked(self):
        """
        Ouvre directement la fenêtre de sélection d'un site CEN
        quand l'utilisateur clique sur le bouton radio 'Site CEN'.
        """

        if not self.radio_site_cen.isChecked():
            return

        self.open_site_cen_selector()


    def on_layer_item_changed(self, item):
        """
        Mémorise l'état coché/décoché d'une couche quand l'utilisateur modifie
        la liste dans l'interface du plugin.
        """
        layer_id = item.data(QT_USER_ROLE)
        if layer_id:
            self.layer_check_states[layer_id] = item.checkState()
        self.update_layers_counter()


    def get_output_folder(self):
        """
        Retourne le dossier de sortie saisi dans l'interface.
        """

        return self.line_dossier_sortie.text().strip()

    def _init_defaults(self):
        """
        Initialise les valeurs par défaut de l'interface.
        """

        # Mode zone par défaut : dessin.
        self.radio_dessiner.setChecked(True)

        # Suffixe par défaut.
        if not self.line_suffixe.text().strip():
            self.line_suffixe.setText("export")

        # Résolution WMS par défaut.
        if self.combo_resolution_wms.count() > 1:
            self.combo_resolution_wms.setCurrentIndex(1)


        # Pyramides raster actives par défaut.
        self.check_pyramides_raster.setChecked(True)

        # Mise à jour de l'état des options.
        self.on_options_changed()

        # Progression et statut.
        self.progress_bar.setValue(0)
        self.lbl_zone_status.setText("Zone : aucune")

        # Mise à jour mode zone et nom fichier.
        self.on_zone_mode_changed()
        self.update_output_filename()


    def ouvrir_selecteur_site_cen(self):
        """
        Ouvre la fenêtre de sélection d'un site CEN quand l'utilisateur clique
        sur le mode 'Site CEN'.
        """

        if not self.radio_site_cen.isChecked():
            return

        dlg = SelecteurSiteCEN(
            pg_service_path=self.pg_service_path,
            pg_service_name="bd CEN (admin)",
            parent=self
        )

        result = exec_dialog(dlg)

        if result != QDIALOG_ACCEPTED:
            self.log("Sélection du site CEN annulée.")

            if self.zone_etude is None:
                self.radio_dessiner.setChecked(True)

                if hasattr(self, "lbl_site_cen_selectionne"):
                    self.lbl_site_cen_selectionne.setText("Site sélectionné : aucun")

                self.lbl_zone_status.setText("Zone : aucune")

            return

        codesitep = dlg.selected_codesitep
        nomsitep = dlg.selected_nomsitep
        communes = dlg.selected_communes

        if not codesitep:
            self.log("Aucun site CEN sélectionné.")
            self.radio_dessiner.setChecked(True)
            return

        zone = charger_zone_bdd(
            codesitep=codesitep,
            nomsitep=nomsitep,
            communes=communes,
            pg_service_path=self.pg_service_path
        )

        if zone is None:
            self.log("Erreur : impossible de charger le site CEN depuis la BDD.")
            self.radio_dessiner.setChecked(True)
            self.lbl_zone_status.setText("Zone : erreur chargement site CEN")
            return

        self.zone_etude = zone
        self.zone_source = "site_cen"

        self.selected_codesitep = codesitep
        self.selected_nomsitep = nomsitep
        self.selected_communes = communes

        if communes:
            texte_site = f"{nomsitep} - {communes} ({codesitep})"
        else:
            texte_site = f"{nomsitep} ({codesitep})"

        if hasattr(self, "lbl_site_cen_selectionne"):
            self.lbl_site_cen_selectionne.setText(
                f"Site sélectionné : {texte_site}"
            )

        self.lbl_zone_status.setText(
            f"Zone : site CEN - {texte_site}"
        )

        self.log(f"Site CEN chargé : {texte_site}")





    # -------------------------------------------------------------------------
    # Logs
    # -------------------------------------------------------------------------

    def log(self, message, level="info"):
        if not getattr(self, "debug_logs", False):
            return
        from qgis.core import QgsMessageLog, Qgis
        message = str(message)
        niveaux = {
            "info": Qgis.Info,
            "warning": Qgis.Warning,
            "critical": Qgis.Critical,
        }
        qgis_level = niveaux.get(level, Qgis.Info)
        print(message)
        QgsMessageLog.logMessage(
            message,
            "Export SIG Zone Etude",
            qgis_level
        )


    # -------------------------------------------------------------------------
    # Zone d'étude
    # -------------------------------------------------------------------------

    def on_zone_mode_changed(self):
        """
        Active ou désactive les éléments selon le mode choisi.
        Cette méthode ne doit PAS ouvrir la fenêtre de sélection CEN.
        """

        mode_dessin = self.radio_dessiner.isChecked()
        mode_site_cen = self.radio_site_cen.isChecked()

        # Le bouton de dessin est actif uniquement en mode dessin
        self.btn_activer_dessin.setEnabled(mode_dessin)

        if mode_dessin:
            self.zone_source = "dessin"
            self.log("Mode zone d'étude : dessin manuel.")

        elif mode_site_cen:
            self.zone_source = "site_cen"
            self.log("Mode zone d'étude : site CEN.")


    def activate_draw_tool(self):
        """
        Active l'outil de dessin du polygone sur la carte QGIS.
        """

        if not self.radio_dessiner.isChecked():
            self.radio_dessiner.setChecked(True)

        self.zone_source = "dessin"

        layer_ids = self.get_checked_layer_ids()

        if not layer_ids:
            QMessageBox.warning(
                self,
                "Aucune couche sélectionnée",
                "Veuillez sélectionner au moins une couche avant de dessiner la zone d'étude."
            )
            return

        if self.iface is None:
            self.log("Erreur : iface QGIS indisponible.")
            return

        canvas = self.iface.mapCanvas()

        self.outil_dessin = OutilDessinPolygone(
            canvas,
            self.on_zone_dessin_terminee
        )

        canvas.setMapTool(self.outil_dessin)

        self.lbl_zone_status.setText(
            "Zone : dessin en cours - clic gauche pour ajouter des points, clic droit pour terminer"
        )

        self.log("Outil de dessin activé.")
        self.log("Clic gauche pour ajouter des points.")
        self.log("Clic droit pour terminer le polygone.")

    def on_zone_dessin_terminee(self, zone):
        """
        Appelée quand l'utilisateur termine le dessin avec un clic droit.
        """

        if zone is None:
            self.log("Erreur : zone dessinée invalide.")
            return

        self.zone_etude = zone
        self.zone_geometry = zone.getGeometrie()
        self.zone_source = "dessin"

        zone.enregistrerCommeCouche()

        self.lbl_zone_status.setText("Zone : dessin manuel terminé")

        if hasattr(self, "lbl_site_cen_selectionne"):
            self.lbl_site_cen_selectionne.setText("Site sélectionné : aucun")

        self.log("Zone dessinée enregistrée.")
        self.log(f"Source     : {zone.getSource()}")
        self.log(f"BoundingBox: {zone.getBoundingBox()}")

        if self.iface is not None:
            self.iface.actionPan().trigger()

    def filter_sites_cen(self, text):
        """
        Filtre la liste des sites CEN affichée dans list_sites_cen.

        Non connectée actuellement : la sélection d'un site passe par
        SelecteurSiteCEN (voir ouvrir_selecteur_site_cen). Ancienne piste
        de recherche inline, à reprendre ou supprimer selon le besoin.

        :param text: texte saisi dans la recherche
        """

        search_text = text.strip()
        if search_text:
            self.log(f"Recherche site CEN : {search_text}")

    def on_site_cen_selected(self):
        """
        Réagit à la sélection d'un site dans list_sites_cen.

        Non connectée actuellement, pour la même raison que filter_sites_cen.
        """

        items = self.list_sites_cen.selectedItems()
        if not items:
            return

        item = items[0]
        site_data = item.data(QT_USER_ROLE)

        self.zone_source = "site_cen"

        self.lbl_zone_status.setText(f"Zone : site CEN sélectionné - {item.text()}")
        self.log(f"Site CEN sélectionné : {item.text()}")

    # -------------------------------------------------------------------------
    # Couches visibles
    # -------------------------------------------------------------------------

    def refresh_visible_layers(self):
        """
        Actualise la liste des couches visibles dans QGIS.

        Important :
        - les couches visibles dans QGIS sont affichées dans le plugin ;
        - les choix cochés/décochés dans le plugin sont conservés ;
        - une nouvelle couche visible est cochée par défaut.
        """

        self._save_current_layer_check_states()

        self.list_couches.blockSignals(True)
        self.list_couches.clear()

        visible_layers = self.get_visible_layers()

        for layer in visible_layers:
            layer_id = layer.id()

            item = QListWidgetItem(self._layer_label(layer))
            item.setData(QT_USER_ROLE, layer_id)

            # Si l'utilisateur avait déjà coché/décoché cette couche dans le plugin,
            # on restaure son choix.
            if layer_id in self.layer_check_states:
                item.setCheckState(self.layer_check_states[layer_id])
            else:
                # Nouvelle couche visible : cochée par défaut.
                item.setCheckState(QT_CHECKED)

            self.list_couches.addItem(item)

        self.list_couches.blockSignals(False)

        self.update_layers_counter()
        self.log(f"{len(visible_layers)} couche(s) visible(s) détectée(s).")

    def _save_current_layer_check_states(self):
        """
        Sauvegarde l'état actuel des cases de la liste des couches.

        Cela permet de conserver les choix de l'utilisateur quand il clique
        sur Actualiser.
        """

        for index in range(self.list_couches.count()):
            item = self.list_couches.item(index)
            layer_id = item.data(QT_USER_ROLE)

            if layer_id:
                self.layer_check_states[layer_id] = item.checkState()

    def select_all_layers(self):
        """
        Coche toutes les couches affichées dans le plugin.
        """

        self._set_all_layers_check_state(QT_CHECKED)
        self.log("Toutes les couches affichées ont été sélectionnées.")


    def deselect_all_layers(self):
        """
        Décoche toutes les couches affichées dans le plugin.
        """

        self._set_all_layers_check_state(QT_UNCHECKED)
        self.log("Toutes les couches affichées ont été désélectionnées.")


    def _set_all_layers_check_state(self, check_state):
        """
        Applique un état coché/décoché à toutes les couches affichées.
        """

        self.list_couches.blockSignals(True)

        for index in range(self.list_couches.count()):
            item = self.list_couches.item(index)
            item.setCheckState(check_state)

            layer_id = item.data(QT_USER_ROLE)
            if layer_id:
                self.layer_check_states[layer_id] = check_state

        self.list_couches.blockSignals(False)

        self.update_layers_counter()

    def update_layers_counter(self):
        """
        Met à jour le nombre de couches visibles et sélectionnées dans le plugin.
        """

        total = self.list_couches.count()
        selected = 0

        for index in range(total):
            item = self.list_couches.item(index)

            if item.checkState() == QT_CHECKED:
                selected += 1

        self.lbl_couches_visibles.setText(
            f"Couches visibles : {total} | sélectionnées : {selected}"
        )


    def get_visible_layers(self):
        """
        Retourne les couches visibles du projet QGIS.

        La notion de visibilité utilisée ici correspond aux couches cochées
        dans l'arbre des couches QGIS.

        :return: liste de QgsMapLayer
        """

        project = QgsProject.instance()
        root = project.layerTreeRoot()

        visible_layers = []

        for layer in project.mapLayers().values():
            node = root.findLayer(layer.id())

            if node is None:
                continue

            try:
                is_visible = bool(node.isVisible())
            except AttributeError:
                # Fallback prudent si l'API évolue.
                # Dans QGIS 3, isVisible() est public sur QgsLayerTreeNode.
                is_visible = True

            if is_visible:
                visible_layers.append(layer)

        return visible_layers

    def _layer_label(self, layer):
        """
        Construit un libellé lisible pour une couche.

        :param layer: QgsMapLayer
        :return: texte affiché dans la liste
        """

        layer_type = "Couche"

        if isinstance(layer, QgsVectorLayer):
            layer_type = "Vecteur"
        elif isinstance(layer, QgsRasterLayer):
            provider = ""
            try:
                provider = layer.providerType()
            except Exception:
                provider = ""

            if provider.lower() in ("wms", "wmts"):
                layer_type = "WMS/WMTS"
            else:
                layer_type = "Raster"

        return f"{layer.name()} [{layer_type}]"

    def get_checked_layer_ids(self):
        """
        Retourne les identifiants des couches cochées dans list_couches.

        :return: liste d'identifiants de couches QGIS
        :rtype: list[str]
        """

        layer_ids = []

        for index in range(self.list_couches.count()):
            item = self.list_couches.item(index)

            if item.checkState() == QT_CHECKED:
                layer_id = item.data(QT_USER_ROLE)
                if layer_id:
                    layer_ids.append(layer_id)

        return layer_ids

    # -------------------------------------------------------------------------
    # Sortie
    # -------------------------------------------------------------------------

    def browse_output_folder(self):
        """
        Ouvre une fenêtre pour choisir le dossier de sortie.
        """

        dossier = QFileDialog.getExistingDirectory(
            self,
            "Choisir le dossier de sortie"
        )

        if not dossier:
            return

        self.line_dossier_sortie.setText(dossier)
        self.update_output_filename()


    def get_output_suffix(self):
        """
        Retourne le suffixe nettoyé pour le nom du fichier.
        """

        suffixe = self.line_suffixe.text().strip()

        if not suffixe:
            suffixe = "export"

        suffixe = suffixe.replace(" ", "_")

        caracteres_interdits = ['\\', '/', ':', '*', '?', '"', '<', '>', '|']

        for caractere in caracteres_interdits:
            suffixe = suffixe.replace(caractere, "_")

        return suffixe


    def get_output_filename(self):
        """
        Retourne le nom du fichier GeoPackage.
        """

        date_inv = datetime.now().strftime("%Y%m%d")
        suffixe = self.get_output_suffix()

        return f"{date_inv}_SIG_{suffixe}.gpkg"


    def get_output_path(self):
        """
        Retourne le chemin complet du GeoPackage de sortie.
        """

        dossier = self.line_dossier_sortie.text().strip()

        if not dossier:
            return ""

        nom_fichier = self.get_output_filename()

        return os.path.join(dossier, nom_fichier)


    def update_output_filename(self):
        """
        Met à jour le label qui affiche le nom du fichier de sortie.
        """

        nom_fichier = self.get_output_filename()
        self.lbl_fichier_sortie.setText(nom_fichier)


    # -------------------------------------------------------------------------
    # Options
    # -------------------------------------------------------------------------
    def init_options(self):
        """
        Initialise les options raster.
        """

        # Résolution WMS
        self.combo_resolution_wms.clear()

        self.combo_resolution_wms.addItem("0.1 m - très haute résolution", 0.1)
        self.combo_resolution_wms.addItem("0.25 m - haute résolution", 0.25)
        self.combo_resolution_wms.addItem("0.5 m - bonne résolution", 0.5)
        self.combo_resolution_wms.addItem("1 m - standard", 1.0)
        self.combo_resolution_wms.addItem("2 m - moyenne", 2.0)
        self.combo_resolution_wms.addItem("5 m - basse résolution", 5.0)
        self.combo_resolution_wms.addItem("10 m - très basse résolution", 10.0)

        # Par défaut : 1 m
        self.combo_resolution_wms.setCurrentIndex(3)

        # Pyramides raster
        self.check_pyramides_raster.setChecked(True)

        self.on_options_changed()

    def on_options_changed(self):
        """
        Met à jour l'interface selon les options.
        """
        pass

    def get_options(self):
        """
        Retourne les options choisies dans l'interface.
        """

        resolution_wms = self.combo_resolution_wms.currentData()

        if resolution_wms is None:
            resolution_wms = 1.0

        return {
            "resolution_wms": float(resolution_wms),
            "pyramides_raster": self.check_pyramides_raster.isChecked(),
        }



    # -------------------------------------------------------------------------
    # Lancement du traitement
    # -------------------------------------------------------------------------

    def validate_before_run(self):
        """
        Vérifie les paramètres avant lancement du découpage.

        :return: True si les paramètres sont valides, sinon False
        """

        output_folder = self.get_output_folder()

        if not output_folder:
            self.log("Erreur : aucun dossier de sortie sélectionné.")
            return False

        if not os.path.isdir(output_folder):
            self.log("Erreur : le dossier de sortie n'existe pas.")
            return False

        checked_layer_ids = self.get_checked_layer_ids()

        if not checked_layer_ids:
            self.log("Erreur : aucune couche sélectionnée pour le découpage.")
            return False

        if self.zone_etude is None:
            self.log("Erreur : aucune zone d'étude définie (dessin ou site CEN).")
            return False

        return True

    def run_decoupage(self):
        """
        Lance le découpage des couches sélectionnées avec la zone d'étude.
        """

        # 1. Vérifications avant lancement
        if not self.validate_before_run():
            return

        # 2. Récupération de la zone d'étude
        zone = self.zone_etude

        if zone is None:
            QMessageBox.warning(
                self,
                "Zone d'étude manquante",
                "Veuillez dessiner une zone ou sélectionner un site CEN."
            )
            return

        # 3. Récupération du fichier de sortie
        output_path = self.get_output_path()

        if not output_path:
            QMessageBox.warning(
                self,
                "Fichier de sortie manquant",
                "Veuillez choisir un dossier de sortie."
            )
            return

        # 4. Récupération des couches sélectionnées
        layer_ids = self.get_checked_layer_ids()

        if not layer_ids:
            QMessageBox.warning(
                self,
                "Aucune couche sélectionnée",
                "Veuillez sélectionner au moins une couche à découper."
            )
            return

        # 5. Si le GeoPackage existe déjà, demander confirmation
        if os.path.exists(output_path):
            reponse = QMessageBox.question(
                self,
                "GeoPackage existant",
                f"Le fichier existe déjà :\n\n{output_path}\n\n"
                "Les couches existantes portant le même nom pourront être remplacées.\n\n"
                "Continuer ?",
                QMessageBox.Yes | QMessageBox.No,
                QMessageBox.No
            )

            if reponse == QMessageBox.No:
                self.log("Découpage annulé : fichier de sortie existant.")
                return

        # 6. Logs interface
        self.progress_bar.setValue(0)

        self.log("Lancement du découpage.")
        self.log(f"Source zone : {zone.getSource()}")
        self.log(f"Fichier de sortie : {output_path}")
        self.log(f"Nombre de couches sélectionnées : {len(layer_ids)}")

        if hasattr(zone, "getCodeSite") and zone.getCodeSite():
            self.log(f"Code site : {zone.getCodeSite()}")

        if hasattr(zone, "getNomSite") and zone.getNomSite():
            self.log(f"Nom site : {zone.getNomSite()}")

        # 7. Lancement réel du découpage
        try:
            options = self.get_options()
            self.log(f"Options : {options}")

            decouper_couches_par_zone(
                zone_etude=zone,
                chemin_gpkg=output_path,
                layer_ids=layer_ids,
                options=options,
                parent=self
            )

            self.progress_bar.setValue(100)
            self.log("Découpage terminé.")

        except Exception as e:
            self.progress_bar.setValue(0)

            self.log(f"Erreur pendant le découpage : {e}")

            QMessageBox.critical(
                self,
                "Erreur pendant le découpage",
                str(e)
            )
