# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportZonePlugin
                                 A QGIS plugin
 Découpage des couches QGIS selon une zone d'étude dessinée ou issue de la BDD CEN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by LAKRIOUCH IKRAM
        email                : lakriouchikram@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from . import resources  # noqa: F401

from .export_sig_zone_etude_dialog import ExportZonePluginDialog


class ExportZonePlugin:
    """Classe principale du plugin QGIS, instanciée via classFactory(iface)."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        self.translator = None
        self.actions = []
        self.dlg = None

        self.menu = self.tr("&Export SIG Zone Etude")
        self.first_start = True

        self._init_translation()

    def _init_translation(self):
        locale = QSettings().value("locale/userLocale", "fr")
        locale = str(locale)[0:2]

        locale_path = os.path.join(
            self.plugin_dir,
            "i18n",
            "ExportZonePlugin_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            if self.translator.load(locale_path):
                QCoreApplication.installTranslator(self.translator)

    def tr(self, message):
        return QCoreApplication.translate("ExportZonePlugin", message)

    def _get_icon(self):
        resource_icon = ":/plugins/export_sig_zone_etude/icon.png"
        icon = QIcon(resource_icon)

        if not icon.isNull():
            return icon

        fallback_icon = os.path.join(self.plugin_dir, "icon.png")
        return QIcon(fallback_icon)

    def add_action(
        self,
        icon,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ):
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip:
            action.setStatusTip(status_tip)

        if whats_this:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        self.add_action(
            icon=self._get_icon(),
            text=self.tr("Export SIG par zone d'étude"),
            callback=self.run,
            parent=self.iface.mainWindow(),
            status_tip=self.tr("Découper les couches QGIS selon une zone d'étude")
        )

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

        self.actions = []

        if self.translator is not None:
            QCoreApplication.removeTranslator(self.translator)
            self.translator = None

        self.dlg = None

    def run(self):
        """Ouvre la fenêtre du plugin. Le traitement est lancé depuis
        btn_lancer_decoupage dans export_sig_zone_etude_dialog.py."""
        if self.first_start or self.dlg is None:
            self.first_start = False

            self.dlg = ExportZonePluginDialog(
                iface=self.iface,
                parent=self.iface.mainWindow()
            )

        self.dlg.show()
        self.dlg.raise_()
        self.dlg.activateWindow()
